[project]
channels = ["conda-forge"]
name = "hhnk-threedi-tools"
platforms = ["win-64", "linux-64", "osx-arm64"]
repository = "https://github.com/threedi/hhnk-threedi-tools"


[target.win-64.tasks]
hrt-install = "bin/pixi/install_hrt.cmd"
hydamo_validation-install = "bin/pixi/install_hydamo_validation.cmd"

[target.linux-64.tasks]
hrt-install = "bash bin/pixi/install_hrt.sh"
hydamo_validation-install = "bin/pixi/install_hydamo_validation.sh"

[target.osx-arm64.tasks]
hrt-install = "bash bin/pixi/install_hrt.sh"
hydamo_validation-install = "bin/pixi/install_hydamo_validation.sh"


[tasks]
#Starting vs code using vs-code.cmd (pixi run code)
lab = "jupyter lab"
code = "code"
code_insiders = "code-insiders"

pre-commit-install = "pre-commit install --install-hooks -t=pre-push" #-t=pre-commit
postinstall = { depends-on = ["hrt-install", "hydamo_validation-install", "pre-commit-install"] }

pre-commit-run = "pre-commit run --all-files"

# Upload to PyPi to make it available with pip
upload_pypi = "twine upload --repository hhnk-threedi-tools  dist/*"

#Styling
sort_imports = "ruff check  ./**/*.py --select I --fix --force-exclude"
fmt = "ruff format ./**/*.py --force-exclude"
style = {depends-on = ["sort_imports", "fmt"]} # `pixi run style`


[feature.dev.tasks]
build_wheels = "rm -rf dist/ && python -m build" # build wheels
twine_check = "twine check dist/*"
build = { depends-on = ["build_wheels", "twine_check"] }


# FIXME set env to 'test' here once we switch to py312. Run tests with; pixi run -e py39 tests
# FIXME change env in pytests_threedi_tools.yml as well
[feature.py39.tasks]
tests = "pytest --cov-report term-missing --cov=hhnk_threedi_tools --cov-report=xml"
sort_imports-check = "ruff check  ./**/*.py --select I --force-exclude"
fmt-check = "ruff format ./**/*.py --check --force-exclude"
style-check = {depends-on = ["sort_imports-check", "fmt-check"]} # raises errors instead of fixing


[dependencies]
python = "3.12.*"
# MI 3.40 site packages
geopandas = "==1.0.1"
numpy = "==1.26.4"
openpyxl = "*"  # 3.1.2
pandas = "==2.2.2"
scipy = "==1.13.0"
urllib3 = "2.*" #2.2.3

# modellen repo deps
gitpython = "*"

# HHNK deps
cached_property = "*"
dask = "*"
folium = "*"
gdal = "*"
# See also: https://discourse.matplotlib.org/t/latest-versions-via-pip-jupyterlab-import-of-matplotlib-broken/24477/7
matplotlib = "*"  # 3.9.0 gives RuntimeError: Entry point name 'inline' duplicated
rasterstats = "*"
rioxarray = "*"
rtree = "*"
ruff = "*"
seaborn = "*"
oracledb = "*"
pyogrio = "*"
pytest = "*"
pytest-cov = "*"
tqdm = "*"
xarray = "*"

pip = "*"

[pypi-dependencies]
# NenS deps
threedi-api-client = "==4.1.12"
threedi-modelchecker = "==2.18.3"
threedi-schema = "==0.300.26"
threedi-scenario-downloader = "*"
threedi_mi_utils = "==0.1.10"
threedigrid = "==2.3.5"
threedidepth = "==0.6.3"
lazy_loader= "*"

# modellen repo deps
gitpython="==3.1.44"

# HHNK deps
hhnk-threedi-tools = { path = ".", editable = true }

[target.win-64.pypi-dependencies]
threedigrid-builder = ">=1.24.3"

[target.linux-64.pypi-dependencies]
threedigrid-builder = ">=1.24.3"

[feature.dev.dependencies]
jupyterlab = "*"
ipywidgets = "*"
jupytext = "*"
pre-commit = "*"
twine="*"

# Datachecker
flask = "*"  # oude datachecker
sqlparse = "*"  # oude datachecker
psycopg2 = "*"  # oude datachecker
fastapi = "*"  # nieuwe datachecker
uvicorn = "*"  # nieuwe datachecker
django = "<4"  # datachecker (<4 wegens compatibility met 3Di modules)


[feature.dev.pypi-dependencies]
# Editable installs, not installed on test. #FIXME doesnt work on Github Actions.
# https://github.com/prefix-dev/pixi/issues/2763
# FIXME disabled. should run pixi run postinstall
# hhnk-research-tools = { path = "../hhnk-research-tools", editable = true }
build = "*"


[feature.test.pypi-dependencies]
hhnk-research-tools = { git = "https://github.com/hhnk/hhnk-research-tools.git", rev = "main" }
hydamo_validation = { git = "https://github.com/hhnk/HyDAMOValidatieModule.git", rev = "main" }


# Temporary old py39 env to have working tests
[feature.py39.dependencies]
python = "==3.9.18" # equals MI python version
geopandas = "==0.14.1"
pandas = "==2.0.2"
scipy = "==1.10.1"
h5py = "*" # Incompatible met rest van env; conda solved naar 3.11.0
fiona = "==1.9.5"
shapely = "==2.0.2"

#User folder
jupyterlab = "==4.2.0"
ipywidgets = "==8.1.2"
jupytext = "==1.16.6"

pytest = "*"
pytest-cov = "*"
tqdm = "==4.64.0"
rioxarray = "==0.15.0" # higher versions need python >=3.10
pyogrio = "==0.7.2" # 0.9.0 doesnt work with gdal
rasterio = "==1.3.10" # rxr dep
affine = "==2.4.0" # rxr dep
dask = "==2024.6.2" # rxr dep
matplotlib = "3.8.*" # 3.9.0 gives RuntimeError: Entry point name 'inline' duplicated
# See also: https://discourse.matplotlib.org/t/latest-versions-via-pip-jupyterlab-import-of-matplotlib-broken/24477/7

xarray = "==2024.3.0"
openpyxl = "==3.1.2"
cached_property = "==1.5.2"
rtree = "==1.0.1"
oracledb = "==2.4.1"
seaborn = "*"
pip = "*"
urllib3= "1.*"

ruff = "*"


[feature.py39.pypi-dependencies]
lazy_loader= "*"
threedi_modelchecker = "==2.6.3" # threedi_results_analysis 3.9.0
threedi_scenario_downloader = "==1.4" # Lizard API v4 only
threedi_schema = "==0.219.3" # threedi_results_analysis 3.9.0
threedi-api-client = "==4.1.7" # 3Di Models and Simulations 3.11.0
threedigrid = "==2.3.3" # threedi_results_analysis 3.12.0
threedidepth = "==0.6.3" # threedi_results_analysis 3.9.0
hhnk-research-tools = { git = "https://github.com/hhnk/hhnk-research-tools.git", rev = "main" }
# hydamo_validation = { git = "https://github.com/hhnk/HyDAMOValidatieModule.git", rev = "main" }

# editable installs
hhnk_threedi_tools = { path = ".", editable = true }

[feature.py39.target.win-64.pypi-dependencies]
threedigrid_builder = "==1.14.4" # threedi_results_analysis 3.9.2

[feature.py39.target.linux-64.pypi-dependencies]
threedigrid_builder = "==1.14.4" # threedi_results_analysis 3.9.2

[environments]
dev = ["dev"]
test = { features=["test"], no-default-feature = false }
py39 = { features=["py39"], no-default-feature = true }
